### ISSUE TITLE
Sequencing on historical data vs real up to date WP data

### ISSUE THREAD

**Issue by kalamartin** [kbss-cvut/react-maintenance-planner#10]
CSAT would like to have workplan based on historical data built and visualized. However, when WP would start, workplan should be amended with actual data exported from AMOS, available now on FTP.
Example: TASK 291000-20-1-600 planned on Friday 1.1.2021. Actually performed on Monday the forth. The blue "rectangle" would be erased 

![Výstřižek1](https://user-images.githubusercontent.com/92854907/158760806-40fadadc-5edb-4bb4-a8b7-d1c03715d36b.PNG)

**Comment by blcham** [comment]
Closed in favour of https://github.com/kbss-cvut/csat-maintenance-planner/issues/4.
