### ISSUE TITLE
Implement CR of milestones

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/react-maintenance-planner#23]
Related to:
RQ4 Milníky (M)
Na časové ose plánovací komponenty je možné 
- **Zobrazovat**
- **Přidávat**
- Upravovat (pohybovat v čase)
- Odebíra`t milníky. 

Need to implement only emphasized points.

**Comment by PluharVit** [comment]
Only the display of milestones is implemented yet. There are new issues for another actions.
