### ISSUE TITLE
Undo and Redo buttons should also affect editing/removal/addition of resources and tasks

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/react-maintenance-planner#39]
@PluharVit @blcham 

Undo / Redo buttons should also work for:

- Editing
    - [x] Resources
    - [x] Tasks
- Removing
    - [x] Resources
- Reordering
    - [x] Resources (Not implemented yet, see #40 )
- Adding (Not implemented yet, see #37 )
    - [x] Resources
    - [x] Tasks

**Comment by blcham** [comment]
Maybe reordering resources, from this:
```
- A
  - B  
  - C
```

To this:
```
- A
  - C  
  - B
```

**Comment by LaChope** [comment]
Agree, I updated the issue
