### ISSUE TITLE
Close finished issues

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/react-maintenance-planner#49]
@PluharVit Many issues that are in "done" are not closed. Can you go over it and close the ones that are implemented?
https://github.com/kbss-cvut/react-maintenance-planner/projects/1

![image](https://user-images.githubusercontent.com/57750426/178293177-ed8d9942-d824-4b50-a9e3-46dcdd28d138.png)

**Comment by blcham** [comment]
I would revise also highlevel tickets in https://docs.google.com/document/d/1idB7Ylc-RqTfJ9zwOjAtLM3lKXge4JS61NLabDrsJrM/edit#heading=h.9xkxhqf4wdd7 and mark them green.
