### ISSUE TITLE
Add adhoc task

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/react-maintenance-planner#53]
In some cases, user might want to create new group ("area", see https://github.com/kbss-cvut/react-maintenance-planner/issues/57#issue-1305834244). We should be able to create new task there where we can define title and date.

![image](https://user-images.githubusercontent.com/3962237/178951779-f8c8b3ba-6db2-42ec-8fff-21e51bab04d6.png)

- Consider creating it in the existing area (without creating Area 1) and text would include information what part of the area it targets.

- It should have type "remark".

_Originally posted by @blcham in https://github.com/kbss-cvut/csat-maintenance-planner/issues/43#issuecomment-1184219670_

**Comment by blcham** [comment]
@LaChope  Let's describe rationale here.
