### ISSUE TITLE
Support creation of new task

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/react-maintenance-planner#58]
Need to be consistent with creation of milestones - https://github.com/kbss-cvut/react-maintenance-planner/issues/56 and selection of multiple tasks.

Options are:
1) double click - will be visualized by default as a task with a predefined length and will trigger a popup where you would be able to choose the type (e.g. milestone/task-card/work-order/...). By default, there will be some type selected (e.g. task-card). When you choose the type milestone, the underlying visualization of the task will change to a vertical line. The issue here is that you cannot specify the size of the task at the beginning.
2) single click - same as above. The issue is that it collides with moving gesture within the calendar.

@blcham @LaChope @kostobog @kalamartin

**Comment by blcham** [comment]
Similar calendars:
https://stephenchou1017.github.io/scheduler/#/
https://gantt-schedule-timeline-calendar.neuronet.io/gstc/examples/complex-1/index.html

**Comment by LaChope** [comment]
Option 1 was retained. I would also add possibility to remove created task-card from same modal #56 

@PluharVit @blcham @kalamartin

**Comment by LaChope** [comment]
Made in https://github.com/kbss-cvut/react-maintenance-planner/pull/70
