### ISSUE TITLE
Reconnect the project with react-calendar-timeline library

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/react-maintenance-planner#66]
- premisses:
  - it is very hard/time-consuming to migrate to the git history of react-calendar-timeline library (we tried it at the meeting)
  - react-calendar-timeline is not evolving so fast (one minor release = 3 commits in last year)
  - we are not able to cherry-pick changes from react-calendar-timeline library because source JavaScript files were moved to src/components/timeline

I suggest that we make our project more similar to the timeline (if it makes sense) so cherry-picking from react-calendar-timeline to here would be possible (this is the long-term goal), and we will not do it "standard git way" but in some predicable documented way. For the short-term goal, we just want to analyze what the state is and possibly upgrade. 

A/C:
- if it makes sense, the library is updated to the newest version (currently 0.28.0)
- make a pull request (branch compare-to-react-calendar-timeline-0.28.0) that would show what is difference between the actual state of react-calendar-timeline  in react-maintenance-planner and the original timeline-component from which it was copied (related to the commit https://github.com/namespace-ee/react-calendar-timeline/commit/44bed941f395f775fb86626933d55dcbd3401fb7)
- make an analysis of possible migration of src/component/timeline/* back to src/. Is it meaningful to move it there?

@LaChope

**Comment by LaChope** [comment]
- [ ] Move JS files to src/lib to project and cherry pick newest changes from timeline project
- [ ] Move and refactor tests, fixtures and examples

**Comment by LaChope** [comment]
To me it seems that changes in [react-maintenance-planner](https://github.com/kbss-cvut/react-maintenance-planner) from [react-calendar-timeline](https://github.com/namespace-ee/react-calendar-timeline) are really minor. I made a PR were I removed the timeline component and just added it as a package from NPM and to me it behaves the same way (see https://deploy-preview-83--react-maintenance-planner.netlify.app/?path=/story/planning-tool--default).

I couldn't find any majors changes in history when timeline was in [src/components/timeline](https://github.com/kbss-cvut/react-maintenance-planner/tree/main/src/components/timeline), but of course I might be wrong. @PluharVit can you tell what were the modifications?

Therefore, history might not be so important and it would be interesting to contribute to the project or fork it to implement our own solution (virtualization, drag & drop...). To me it seems like the "cleanest" way to do it.

What do you think @blcham @PluharVit ?

**Comment by blcham** [comment]
I'll try to come to the next meeting to discuss it :)

**Comment by LaChope** [comment]
Changes made to timeline:

- Resizable sidebar

@PluharVit Can you  add what is missing

**Comment by LaChope** [comment]
@blcham will fork and create repo for https://github.com/namespace-ee/react-calendar-timeline

**Comment by LaChope** [comment]
> The fork is here: https://github.com/kbss-cvut/react-calendar-timeline

Ticket closed as new repo was created. Following issues can be found in https://github.com/kbss-cvut/react-calendar-timeline/issues/1
