### ISSUE TITLE
Support for selection of subtasks

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/react-maintenance-planner#8]
As a user I would like to see tasks that are subtasks of given task. Upon clicking on the task all subtasks should be highlighted.
It should work on any level of the resource tree (of course it does not make sense for the lower most level as no subtasks would be selected)

![image](https://user-images.githubusercontent.com/3962237/156004765-28cdae7b-9772-41b9-8340-b69a9eb7e94c.png)

**Comment by kalamartin** [comment]
@PluharVit @blcham please see CSAT proposal:

![156004765-28cdae7b-9772-41b9-8340-b69a9eb7e94c](https://user-images.githubusercontent.com/92854907/158759596-2c422e73-cb84-4e37-af1e-4c1725b22108.png)

**Comment by blcham** [comment]
I consider this task to be done, while comment of @kalamartin has been moved to https://github.com/kbss-cvut/react-maintenance-planner/issues/5.
